### ISSUE TITLE
checkmark position offset

### ISSUE THREAD

**Issue by KhaozFrost** [PunishedPineapple/ReadyCheckHelper#2]
![image](https://user-images.githubusercontent.com/15788954/181936765-020dc65c-2258-48bb-9805-3d9015b3b3f5.png)
would you add in the ability to be able to offset the location of the checkmark so that we can use it with partylist layout plugin for custom plists

**Comment by PunishedPineapple** [comment]
That's been in the to do list for a while, but I never got around to it.  I'll try to make it a priority for when I next update the plugin.

**Comment by PunishedPineapple** [comment]
There are options for this in the config window for version 1.0.4.0, which should now be in the plugin installer.
