### ISSUE TITLE
[Feature Request] Attaching to party list

### ISSUE THREAD

**Issue by tokataka** [PunishedPineapple/ReadyCheckHelper#4]
Currently plugin stuffs are placed top of other UI elements like below.

![image](https://user-images.githubusercontent.com/22884343/190893778-215e4774-705f-4c0f-8c8c-82f7d965b895.png)

Could you make it to be attached to party list element not global?

**Comment by PunishedPineapple** [comment]
Ya, it's planned to make it an option to use the game's native UI instead of an ImGui overlay.  I'm not sure when I'll get around to it for sure.  Might be implemented with some work I'm doing over the next few days, or it might be later.

**Comment by tokataka** [comment]
Got it. Thanks!

**Comment by PunishedPineapple** [comment]
This plugin is no longer maintained by me.  The currently active fork should be https://github.com/Infiziert90/ReadyCheckHelper.  Closing this issue in preparation for archiving the repo.
