### ISSUE TITLE
.net7 & api8 incompatability

### ISSUE THREAD

**Issue by MidoriKami** [PunishedPineapple/ReadyCheckHelper#5]
![image](https://user-images.githubusercontent.com/9083275/206936432-a5f36cce-ba42-4b86-b296-c78f95ef520c.png)

There are some upcoming changes to clientstructs that throw exceptions from your plugin.

**Comment by PunishedPineapple** [comment]
Removed in latest version.  That field was never accurate anyway (presumably why it was taken out of CS).
