### ISSUE TITLE
[Feature Request] Sound file played when initiated

### ISSUE THREAD

**Issue by Morphyloon** [PunishedPineapple/ReadyCheckHelper#7]
Could a sound file be played when a Ready Check is initiated in the group? Ideally, more than one could be pointed at and randomly picked to play. I'm not sure if it'd be easier to have a fixed amount of entries (blank would play nothing) or a way of setting up a dynamic list so there would always be at least one and no empty entries.

The idea is blatantly copied from the WoW addon Comix which was hard-coded to use several possible (and included) sound files for the Ready Check.

**Comment by PunishedPineapple** [comment]
Sounds are something that I had wanted to add (as long as the dependencies wouldn't be too bad), but at this point, it is unlikely that my plugins will recieve any further development.  I'm sorry for the trouble.

I'm sure that you probably already know this, but just in case: you can have an ACT trigger play a sound file.  If you use the Triggernometry plugin for ACT, you should be able to set up a trigger that does something like pick a random number to use as an index into a list of file names, and plays that sound file.

**Comment by PunishedPineapple** [comment]
This plugin is no longer maintained by me.  The currently active fork should be https://github.com/Infiziert90/ReadyCheckHelper.  Closing this issue in preparation for archiving the repo.
